### ISSUE TITLE
Api links are deprecated

### ISSUE THREAD

**Issue by lahgazisafae** [learn-co-curriculum/boozer-practice-code-challenge#1]
I think this is a great practice challenge! Is it possible to get the data in a json file(s) instead of hosted on heroku? Or is there a particular reason why this challenge is no longer available? 
Thanks!

**Comment by maxwellbenton** [comment]
Hi @lahgazisafae,

Thank you for providing this feedback. This challenge was taken out of use after repeated feedback from students related to the content of the API.

We want to provide a welcome and inclusive space for all students, and it was decided that alcohol-centered projects and challenges do not achieve that. However, as this challenge is good practice for using APIs in React, I've added this issue to a separate, general issue we are using to organize upcoming work on our React curriculum.

As this challenge is deprecated, I'm closing this issue but I invite you to follow the progress on React issues [here](https://github.com/learn-co-curriculum/this-is-react-readme/issues/3). We will notify
you here when this challenge is updated or replaced.

Thank you for contributing!
